In [2]:
import numpy as np

In [15]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [5]:
b = np.array([[9.08, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9.08, 8.  , 7.  ],
       [6.  , 5.  , 4.  ]])

In [6]:
# Get Dimension
a.ndim

1

In [8]:
# Get shape
b.shape

(2, 3)

In [12]:
# Get type
a.dtype

dtype('int16')

In [16]:
# Get size of bites
a.itemsize

4

In [19]:
# Get total size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [20]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [21]:
a.shape

(2, 7)

In [22]:
# Get a specific element [r, c]
a[1, 5]

13

In [24]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [25]:
# Get a specific columns
a[:, 2]

array([ 3, 10])

In [29]:
# [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [30]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [32]:
a[:, 2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [33]:
# 3-d example
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [35]:
# Get a specific element (work outside in)
b[0,1,1]

4

In [37]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

In [39]:
# replace
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Diffrent Types of Arrays

In [40]:
# All 0s metrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
# All 1s metrix
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [46]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [47]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.43667902, 0.04517734],
       [0.14269834, 0.45219231],
       [0.22872189, 0.22845422],
       [0.14374354, 0.25081879]])

In [53]:
# Random decimal numbers like other array
np.random.random_sample(a.shape)

array([[0.57782299, 0.24144758, 0.01038578, 0.81985547, 0.40508014,
        0.2034008 , 0.56954678],
       [0.94408865, 0.97680687, 0.14272702, 0.38882526, 0.46095239,
        0.31474592, 0.2493946 ]])

In [62]:
# Random Integer values
np.random.randint(-4, 8, size=(3,3))

array([[ 5,  0, -1],
       [ 7, -1,  1],
       [-3,  1,  5]])

In [65]:
# The index matrix
np.identity(3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [72]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [83]:
# My solution
c = np.ones(shape=(5,5))
c[1:4, 1:4] = 0
c[2,2] = 9
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [90]:
# Other solution
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays !!

In [95]:
# .copy()
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Math

In [96]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [97]:
a + 2

array([3, 4, 5, 6])

In [98]:
a - 2

array([-1,  0,  1,  2])

In [99]:
a * 2

array([2, 4, 6, 8])

In [100]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [103]:
b = np.array([1, 0, 1, 0])
a + b

array([4, 4, 6, 6])

In [104]:
a ** 2

array([ 9, 16, 25, 36])

In [108]:
# Take the sin
np.sin(a)

array([ 0.14065208, -0.68660026, -0.81857414, -0.27579386])

# Linear Algebra

In [110]:
a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [111]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0