In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3])

In [4]:
b = np.array([[9.08, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9.08, 8.  , 7.  ],
       [6.  , 5.  , 4.  ]])

In [5]:
# Get Dimension
a.ndim

1

In [6]:
# Get shape
b.shape

(2, 3)

In [7]:
# Get type
a.dtype

dtype('int32')

In [8]:
# Get size of bites
a.itemsize

4

In [9]:
# Get total size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [11]:
a.shape

(2, 7)

In [12]:
# Get a specific element [r, c]
a[1, 5]

13

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific columns
a[:, 2]

array([ 3, 10])

In [15]:
# [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [17]:
a[:, 2] = [1,2]
a

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 8,  9,  2, 11, 12, 20, 14]])

In [18]:
# 3-d example
b = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [19]:
# Get a specific element (work outside in)
b[0,1,1]

4

In [20]:
b[:, 0, :]

array([[1, 2],
       [5, 6]])

In [21]:
# replace
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Initializing Diffrent Types of Arrays

In [22]:
# All 0s metrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
# All 1s metrix
np.ones((4,2,2), dtype='int16')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int16)

In [24]:
# Any other number
np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [25]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.11998146, 0.30807975],
       [0.72359215, 0.78113012],
       [0.76087918, 0.49809704],
       [0.15053732, 0.07059392]])

In [27]:
# Random decimal numbers like other array
np.random.random_sample(a.shape)

array([[0.81153889, 0.03795221, 0.18754112, 0.09978284, 0.0223099 ,
        0.8734961 , 0.036057  ],
       [0.43003637, 0.9459389 , 0.77897935, 0.80910272, 0.01815977,
        0.70548995, 0.59391853]])

In [28]:
# Random Integer values
np.random.randint(-4, 8, size=(3,3))

array([[5, 7, 4],
       [1, 4, 5],
       [5, 5, 0]])

In [29]:
# The index matrix
np.identity(3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
# Repeat array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [31]:
# My solution
c = np.ones(shape=(5,5))
c[1:4, 1:4] = 0
c[2,2] = 9
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# Other solution
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays !!

In [33]:
# .copy()
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Math

In [34]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [35]:
a + 2

array([3, 4, 5, 6])

In [36]:
a - 2

array([-1,  0,  1,  2])

In [37]:
a * 2

array([2, 4, 6, 8])

In [38]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [40]:
a ** 2

array([ 1,  4,  9, 16])

In [41]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [42]:
a = np.ones((2,3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [43]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [46]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.min(stats)

1

In [56]:
np.max(stats, axis=1)

array([3, 6])

In [57]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing Arrays

In [62]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [63]:
# Vertically stacking vectors elements of vectors must match
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous 
Load Data from File

In [73]:
fileData = np.genfromtxt('D:\Programowanie\Workplace\Code\Data_Science_brick_by_brick\DataScienceSummerStudy\_numpy\data.txt', delimiter=',')
fileData = fileData.astype('int32')
fileData

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Boolean Masking and Advanced Indexing

In [75]:
fileData > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [76]:
fileData[fileData > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [79]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [82]:
np.all(fileData > 50, axis=1)

array([False, False, False])

In [94]:
((fileData > 50) & (fileData < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])